#
# Copyright (C) 2021 Davidson Francis <davidsondfgl@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#

os: linux
dist: focal

language: c

env:
  - CTEST_OUTPUT_ON_FAILURE=1

jobs:
  include:
    - os: linux
      services: docker
      name: "Linux (AMD64) Build & Test"
      script:
        - >
          mkdir build &&
          cd build &&
          cmake ..
          -DCMAKE_BUILD_TYPE=Release
          -DENABLE_WSSERVER_TEST=On &&
          make -j$(nproc) &&
          make test

    - os: linux
      services: docker
      name: "Windows (via Wine) (AMD64) Build & Test"
      before_script: sudo apt-get install mingw-w64 wine64 -y
      script:
        - >
          wget https://git.io/JcAzE -O mingw-w64-x86_64.cmake &&
          mkdir build &&
          cd build &&
          cmake ..
          -DCMAKE_TOOLCHAIN_FILE=../mingw-w64-x86_64.cmake
          -DCMAKE_BUILD_TYPE=Release
          -DENABLE_WSSERVER_TEST=On &&
          make -j$(nproc) &&
          make test

    - os: osx
      name: "macOS (AMD64) (Build)"
    - os: freebsd
      name: "FreeBSD (AMD64) (Build)"
script:
  - >
    mkdir build && cd build &&
    cmake ..
    -DCMAKE_BUILD_TYPE=Release &&
    make -j2
